db:
  image: mariadb
  container_name: db
  restart: unless-stopped
  tty: true
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: laravel_db
    MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    SERVICE_TAGS: dev
    SERVICE_NAME: mariadb
  volumes:
    - /dbdata:/var/lib/mysql/
    - ./mysql/my.cnf:/etc/mysql/my.cnf
  networks:
    - app-network
