FROM php:7.4-fpm
# فایل کامپوزر رو توی ورکینگ دایرکتوری قرار میدیم
COPY composer.lock composer.json /var/www/

# توی این قسمت ورکینگ دایرکتوری خودمون رو مشخص میکنیم
WORKDIR /var/www

# هر دیپندنسی که لازم داریم رو نصب میکنیم
RUN apt-get update --fix-missing && apt-get install -y  \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zlibc \
    mariadb-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    zip

#از اوپکش استفاده میکنیم برای افزایش سرعت اجرای کد های پی اچ پی 
RUN docker-php-ext-install opcache  && docker-php-ext-enable opcache

# کش رو خالی میکنیم
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# اکستنشن های لازم برای لاراول و پی اچ پی رو نصب میکنیم
RUN docker-php-ext-install pdo_mysql exif pcntl
#RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/
RUN docker-php-ext-install bcmath

# کامپوزر رو نصب میکنیم
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# پورت 9000 رو اکسپوز میکنیم . در انتها سرور اف پی ام رو اجرا میکنیم
EXPOSE 9000
CMD ["php-fpm"]
