# Phpmyadmin Service
phpmyadmin:
  depends_on:
    - db
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports:
    - '8082:80'
  environment:
    PMA_HOST: db
    MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
  networks:
    - app-network
    
