version: '3'
services:

    mysql:
        image: 'mysql:5.7'

        container_name: mysql

        restart: always

        environment:

            - MYSQL_ROOT_PASSWORD=EUEBmxTYtgrXdsdsnfHJJwE9V9fKK7Anha

            - MYSQL_DATABASE=wordpress

            - MYSQL_USER=wordpress

            - MYSQL_PASSWORD=EUEBmxTYtgrXdsdsnfHJJwE9V9fKK7Anha

    wordpress:
        image: 'wordpress:latest'      

        container_name: wordpress

        restart: always

        environment:

            - 'WORDPRESS_DB_HOST=mysql:3306'

            - WORDPRESS_DB_USER=wordpress

            - WORDPRESS_DB_PASSWORD=EUEBmxTYtgrXdsdsnfHJJwE9V9fKK7Anha

            - WORDPRESS_DB_NAME=wordpress

        links:

            - 'mysql:db'

    nginx:
        image: 'nginx:latest'

        container_name: nginx

        restart: always

        volumes:

            - '/home/ahmad/DockerMe/wp/nginx/conf.d:/etc/nginx/conf.d'

            - '/home/ahmad/DockerMe/wp/nginx/cert:/etc/nginx/cert'

        ports:

            - '80:80'

            - '443:443'

        links:

            - 'wordpress:wp'
