###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: docker-php-fpm-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: docker-php-fpm-mailhog
      ports:
        - "8080:8025"

    redis:
      image: redis:alpine
      container_name: docker-php-fpm-redis

    mysql:
      image: mysql:8.0
      container_name: docker-php-fpm-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=32547561
        - MYSQL_DATABASE=database_db
        - MYSQL_USER=master
        - MYSQL_PASSWORD=2547561
      ports:
        - "8081:3306"

    mariadb:
      image: mariadb:10.4
      container_name: docker-php-fpm-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=32547561
        - MYSQL_DATABASE=database_db
        - MYSQL_USER=master
        - MYSQL_PASSWORD=2547561
      ports:
        - "8082:3306"

    postgres:
      image: postgres:11.1-alpine
      container_name: docker-php-fpm-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=32547561
        - POSTGRES_PASSWORD=2547561
        - POSTGRES_DB=database_db
      ports:
        - "8083:5432"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: docker-php-fpm-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: docker-php-fpm-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8079:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-php-fpm-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

