version: '3.8'
services:

  bind:
    image: sameersbn/bind:latest
    container_name: bind-server
    restart: always
    environment:
       - ROOT_PASSWORD=2547561
       #- WEBMIN_INIT_SSL_DISABLE
    volumes:
       - /home/master/Bind:/data
    networks:
       - gnsina.net
    ports:
       -  "53:53/tcp"
       -  "53:53/udp"
       -  "10000:10000/tcp"

#Docker Networks
networks:
  gnsina.net:

